apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: ${{ values.imageUrl }}-stage
images:
- name: ${{ values.repoName }}-image
  newName: ${{ values.imageRepository }}/${{ values.imageUrl }}/${{ values.repoName }}
  digest: latest