apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{ values.repoName }}
  name: ${{ values.repoName }}
  namespace: ${{ values.repoName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.repoName }}
  template:
    metadata:
      labels:
        app: ${{ values.repoName }}
    spec:
      containers:
      - image: ${{ values.repoName }}-image
        name: ${{ values.repoName }}
