apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ${{ values.repoName }}
commonLabels:
  app: ${{ values.repoName }}
resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- route.yaml
