apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ${{ values.repoName }}
  name: ${{ values.repoName }}
  namespace: ${{ values.repoName }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ${{ values.repoName }}
