apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ${{ values.repoName }}-pipeline
  namespace: ${{ values.namespace }}
  labels:
    type: pipeline
spec:
  params:
    - name: source-repo
      description: source repo that contains the application code
      type: string
      default: https://${{ values.sourceControl }}/${{ values.orgName }}/${{ values.repoName }}
    - name: source-branch
      description: source branch to build from
      default: main
      type: string
    - name: output-image
      description: reference of the image that will get created
      default: ${{ values.imageRepository }}/${{ values.imageUrl }}/${{ values.repoName }}
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.source-repo)
        - name: revision
          value: $(params.source-branch)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-folder
        - name: basic-auth
          workspace: git-creds
    - name: maven-build
      taskRef:
        kind: ClusterTask
        name: maven
      runAfter:
        - git-clone
      params:
      - name: GOALS
        value:
          - clean
          - package
          - -DskipTests=true
          - -Dquarkus.package.type=uber-jar
      workspaces:
      - name: source
        workspace: source-folder
      - name: maven-settings
        workspace: maven-settings
    - name: scan
      taskRef:
        kind: Task
        name: sonarqube-scanner
      runAfter:
        - maven-build
      params:
      - name: SONAR_HOST_URL
        value: 'http://sonarqube-sonarqube.sonarqube.svc:9000'
      workspaces:
      - name: source
        workspace: source-folder
      - name: sonar-settings
        workspace: sonar-settings
    - name: ${{ values.imageBuilder }}
      params:
        - name: VERSION
          value: latest
        - name: IMAGE
          value: $(params.output-image)
      runAfter:
        - scan
      taskRef:
        kind: ClusterTask
        name: ${{ values.imageBuilder }}
      workspaces:
        - name: source
          workspace: source-folder
  workspaces:
    - name: source-folder
    - name: git-creds
    - name: sonar-settings
    - name: maven-settings